apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-deployment
  labels:
    app: paper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paper
  template:
    metadata:
      labels:
        app: paper
    spec:
      volumes:
        - name: paper-pv-data
          persistentVolumeClaim:
            claimName: paper-pv-claim
      containers:
      - name: paper-container
        image: gcr.io/eminent-century-263110/minecraftserver:latest
        env:
        ports:
        - containerPort: 25565
        readinessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 25565
          initialDelaySeconds: 60
          failureThreshold: 10
          periodSeconds: 20
        volumeMounts:
          - mountPath: "/mnt/data"
            name: paper-pv-data
